(*Global Data SQL Struct*)

TYPE
	DataSQLOperate_typ : 	STRUCT 
		RecipeRead : BOOL;
		RecipeReadStatus : UINT;
		RecipeInsert : BOOL;
		RecipeInsertReq : BOOL;
		ProductRead : BOOL;
		ProductReadStatus : UINT;
		ProductInsert : BOOL;
		ProductInsertReq : BOOL;
		AuditRead : BOOL;
		AuditReadStatus : UINT;
		AuditInsertFault : BOOL;
		AlarmRead : BOOL;
		AlarmReadStatus : UINT;
		AlarmInsertFault : BOOL;
	END_STRUCT;
END_TYPE

(*Global Data SQL Struct*)

TYPE
	DataSQLQueryConfig_typ : 	STRUCT 
		StartTime : ARRAY[0..READ_QUERY_SIZE_MINUS]OF STRING[20];
		EndTime : ARRAY[0..READ_QUERY_SIZE_MINUS]OF STRING[20];
		PointName : ARRAY[0..READ_QUERY_SIZE_MINUS]OF STRING[20];
		AuxQuery : ARRAY[0..READ_QUERY_SIZE_MINUS]OF STRING[80];
	END_STRUCT;
	DataSQLQueryCmd_typ : 	STRUCT 
		Next : BOOL;
	END_STRUCT;
	DataSQLQuery_typ : 	STRUCT 
		Config : DataSQLQueryConfig_typ;
		Cmd : DataSQLQueryCmd_typ;
	END_STRUCT;
END_TYPE

(*Global Data Struct - Recipe*)

TYPE
	DataSQLRecipe_typ : 	STRUCT 
		TimeStamp : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF DATE_AND_TIME;
		TimeStampTS : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TimeStampFB : UDINT;
		State : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		StateTS : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		StateFB : UDINT;
		CH00 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH01 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH02 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH03 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH04 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH05 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH06 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH07 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH08 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH09 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH10 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH11 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH12 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH13 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH14 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH15 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH16 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH17 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH18 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH19 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH20 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH21 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH22 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH23 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH24 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH25 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		TS00 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS01 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS02 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS03 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS04 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS05 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS06 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS07 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS08 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS09 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS10 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS11 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS12 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS13 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS14 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS15 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS16 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS17 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS18 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS19 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS20 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS21 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS22 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS23 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS24 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS25 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		FB00 : UDINT;
		FB01 : UDINT;
		FB02 : UDINT;
		FB03 : UDINT;
		FB04 : UDINT;
		FB05 : UDINT;
		FB06 : UDINT;
		FB07 : UDINT;
		FB08 : UDINT;
		FB09 : UDINT;
		FB10 : UDINT;
		FB11 : UDINT;
		FB12 : UDINT;
		FB13 : UDINT;
		FB14 : UDINT;
		FB15 : UDINT;
		FB16 : UDINT;
		FB17 : UDINT;
		FB18 : UDINT;
		FB19 : UDINT;
		FB20 : UDINT;
		FB21 : UDINT;
		FB22 : UDINT;
		FB23 : UDINT;
		FB24 : UDINT;
		FB25 : UDINT;
	END_STRUCT;
END_TYPE

(*Global Data Struct - Product*)

TYPE
	DataSQLProduct_typ : 	STRUCT 
		TimeStamp : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF DATE_AND_TIME;
		TimeStampTS : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TimeStampFB : UDINT;
		State : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		StateTS : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		StateFB : UDINT;
		CH01 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH02 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH03 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH04 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH05 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		CH06 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF REAL;
		TS01 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS02 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS03 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS04 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS05 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		TS06 : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		FB01 : UDINT;
		FB02 : UDINT;
		FB03 : UDINT;
		FB04 : UDINT;
		FB05 : UDINT;
		FB06 : UDINT;
	END_STRUCT;
END_TYPE

(*Global Data Struct - Alarm*)

TYPE
	DataSQLAlarm_typ : 	STRUCT 
		AlarmIndex : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AlarmCode : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AlarmCodeTS : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AlarmCodeFB : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AlarmTime : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF DATE_AND_TIME;
		AlarmTimeTS : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AlarmTimeFB : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AlarmText : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF WSTRING[50];
		AlarmTextTS : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AlarmTextFB : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AlarmState : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AlarmStateTS : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AlarmStateFB : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AlarmStateStr : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF STRING[80];
		AlarmLastItemIndex : UDINT;
	END_STRUCT;
END_TYPE

(*Global Data Struct - Audit*)

TYPE
	DataSQLAudit_typ : 	STRUCT 
		AuditIndex : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AuditTime : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF DATE_AND_TIME;
		AuditTimeTS : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AuditTimeFB : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AuditOperator : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF WSTRING[15];
		AuditOperatorTS : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AuditOperatorFB : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AuditText : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF WSTRING[100];
		AuditTextTS : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AuditTextFB : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF UDINT;
		AuditTextReport : ARRAY[0..REV_BUFFER_SIZE_MINUS]OF WSTRING[100];
		AuditLastItemIndex : UDINT;
	END_STRUCT;
END_TYPE

(*Global Data Struct - Product*)

TYPE
	DataProduct_typ : 	STRUCT 
		TimeStamp : DATE_AND_TIME;
		State : UDINT;
		CH01 : REAL;
		CH02 : REAL;
		CH03 : REAL;
		CH04 : REAL;
		CH05 : REAL;
		CH06 : REAL;
	END_STRUCT;
END_TYPE
